### ISSUE TITLE
No reconoce comandos de movimiento en esperanto

### ISSUE THREAD

**Issue by Notxor** [komoku/aetheria#313]
Probando la traducción al esperando de Vampiro que estoy haciendo. Al intentar un movimiento simple como ir al norte («norden», «n», «iri norden»...) aparece el mensaje genérico «Ĉu. Kiu vi iras?» lo que quiere decir que detecta que es un movimiento pero no hacia dónde.

**Comment by komoku** [comment]
This issue has long been fixed but I forgot to mark it as fixed.
